feat: Add authorEmailToken
Infomaniak/multiplatform-SwissTransfer pull request #115
Opened 2024-12-11 12:11 UTC by PhilippeWeidmann

2024-12-11 15:05 UTC, tevincent requested changes

2024-12-11 15:05 UTC, tevincent commented on STNetwork/src/commonMain/kotlin/com/infomaniak/multiplatform_swisstransfer/network/models/upload/request/InitUploadBody.kt
> +    val authorEmailToken: String? = null,
We need to find a way to not send this in the API call if it's null.

2024-12-12 14:09 UTC, sirambd approved these changes

2024-12-12 15:13 UTC, tevincent approved these changes

2024-12-12 15:13 UTC, sirambd approved these changes

2024-12-12 15:15 UTC, merged