[i05] refactor: Improve multiplatform targets publish
Infomaniak/multiplatform-SwissTransfer pull request #9
Opened 2024-07-11 14:54 UTC by sirambd

Depends on #8

2024-07-12 13:29 UTC, tevincent requested changes

2024-07-12 13:29 UTC, tevincent commented on Core/build.gradle.kts
> +    id("infomaniak.PublishPlugin")
A typo in the name ?

2024-07-12 13:35 UTC, tevincent approved these changes

2024-07-15 06:11 UTC, tevincent approved these changes

2024-07-16 08:51 UTC, KevinBoulongne requested changes

2024-07-16 08:51 UTC, KevinBoulongne commented on Database/build.gradle.kts
```suggestion
```

2024-07-16 12:08 UTC, KevinBoulongne approved these changes

2024-07-16 14:11 UTC, tevincent approved these changes

2024-07-17 11:38 UTC, merged